# Project information
site_name: Parseltongue
site_url: https://rajtilakjee.github.io/parseltongue/
site_author: Rajtilak Bhattacharjee
site_description: >-
  Personal blog, portfolio, musings.

# Repository
repo_name: rajtilakjee/parseltongue
repo_url: https://github.com/rajtilakjee/parseltongue

# Copyright
copyright: Copyright &copy; 2024 Rajtilak Bhattacharjee

# Configuration
theme:
  name: material
  palette:
    primary: indigo
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - primary: custom
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/favicon.png
  # icon:
  #   logo: logo

# Plugins
plugins:
  - blog:
      archive_date_format: MMMM yyyy
      blog_toc: true
  - tags:
      tags_file: blog/tags.md

# Navigation
nav:
    - Home: index.md
    - Blog:
        - blog/index.md
        Tags: blog/tags.md

# Additional CSS
# extra_css:
#   - stylesheets/extra.css

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rajtilakjee
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/rajtilakjee